services:
  postgres:
    image: postgres:16
    container_name: bundesliga_postgres
    environment:
      POSTGRES_USER: bundesliga
      POSTGRES_PASSWORD: bundesliga_dev
      POSTGRES_DB: bundesliga
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bundesliga_net

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.9.latest
    container_name: bundesliga_dbt
    working_dir: /usr/app/dbt
    volumes:
      - ./dbt:/usr/app/dbt
      - ./dbt/profiles:/root/.dbt
    networks:
      - bundesliga_net
    depends_on:
      - postgres
    entrypoint: [""]
    command: ["sleep", "infinity"]

  airflow:
    image: apache/airflow:2.10.4
    container_name: bundesliga_airflow
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      _AIRFLOW_DB_MIGRATE: "true"
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - airflow_db_data:/opt/airflow
      - ./src:/opt/airflow/src
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    networks:
      - bundesliga_net
    command: standalone
    user: "0:0"
    restart: unless-stopped

volumes:
  postgres_data:
  airflow_db_data:

networks:
  bundesliga_net:
    driver: bridge
